version: "3.8"
services:
  app:
    build: .
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "5001:5000"
    restart: always
  mysql:
    image: mysql:8.0
    # build: ./mysql
    platform: linux/amd64
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: market
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    restart: always
networks:
  python-network:
    driver: bridge
